Description = "The personal blog and home page of one of the web's many Tobys. What distinguishes me is that I own the domain. To you I say welcome(!) in the grand old tradition of proto-websites of the nineties. The place where I deposit the overflow of my time, mind, and labors, Tobyblog is my refuge from the coming social media apocalypse."
RSSEnabled = false
RSSMicropostTitles = false
RSSSections = []
ShowCopyright = true
SummarizeMicroposts = false
YearlyMicroposts = true
images = ["img/tobyblog-site-cover.jpg"]

# Meta Data for SEO

## Homepage
title = "Tobyblog"
titleSeparator = "-"
titleAddition = "Homepage of Toby"

# Images (@hyas/images)
[hyas_images]
  [hyas_images.defaults]
    decoding = "async" # sync, async, or auto (default)
    fetchpriority = "auto" # high, low, or auto (default) 
    loading = "lazy" # eager or lazy (default)
    widths = [1024] # [640, 768, 1024, 1366, 1600, 1920] for example
    sizes = "auto" # 100vw (default), 75vw, or auto for example
    formats = "webp"
#    process = "resize 1024x webp q90 MitchellNetravali" #"fill 780x520" # "fill 1600x900" or "fill 2100x900" for example
    lqip = "1024x webp q50 MitchellNetravali" # "21x webp q20" for example
#   [hyas_images.landscape]
#     normalize = "780x585" # "1600x900" (default)
#     lqip = "4x3" # "16x9" (default)
#     widths = [480, 640, 800, 1024]
#   [hyas_images.portrait]
#     normalize = "780x1040" # "900x1600" (default)
#     lqip = "3x4" # "9x16" (default)
#     widths = [480, 640, 800, 1024]

