## Hugo
title = "Tobyblog"
titleSeparator = "-"
titleAddition = "Homepage of Toby"
description = "The personal blog and home page of one of the web's many Tobys. What distinguishes me is that I own the domain. To you I say welcome(!) in the grand old tradition of proto-websites of the nineties. The place where I deposit the overflow of my time, mind, and labors, Tobyblog is my refuge from the coming social media apocalypse."
images = ["img/tobyblog-site-cover.jpg"]
RSSEnabled = false
RSSMicropostTitles = false
RSSSections = []
ShowCopyright = true
SummarizeMicroposts = false
YearlyMicroposts = true
DisqusShortname = "tobyblog-com"
EnablePreferredDarkAppearance = false

[social]
	twitter = "tobyblog"
	
[Author]
	handle = "tobyblog"
	FirstName = "Toby"
	LastName = "Marks"
	AboutPage = ""
	Location = "Dallas, TX"
	FlickrID = "75738497@N00"
	# FlickrID = "tobyjmarks"
	SocialURL = "https://mastodon.social/@tobyblog"

# Debug
[render_hooks.image]
  errorLevel = 'ignore' # ignore (default), warning, or error (fails the build)

[render_hooks.link]
  errorLevel = 'ignore' # ignore (default), warning, or error (fails the build)
  highlightBroken = false # true or false (default)


# Inline SVG (@thulite/inline-svg)
[inline_svg]
  iconSetDir = "tabler-icons" # "tabler-icons" (default)

# SEO (@thulite/seo)
[seo]
  [seo.title]
    separator = " | "
    suffix = ""
  [seo.favicons]
    sizes = []
    icon = "favicon.png" # favicon.png (default)
    svgIcon = "favicon.svg" # favicon.svg (default)
    maskIcon = "mask-icon.svg" # mask-icon.svg (default)
    maskIconColor = "white" # white (default)
  [seo.schemas]
    type = "Organization" # Organization (default) or Person
    logo = "favicon-512x512.png" # Logo of Organization — favicon-512x512.png (default)
    name = "Tobyblog" # Name of Organization or Person
    sameAs = [] # E.g. ["https://github.com/thuliteio/thulite", "https://fosstodon.org/@thulite"]
    images = ["img/tobyblog-site-cover.jpg"] # ["cover.png"] (default)
    article = [] # Article sections
    newsArticle = [] # NewsArticle sections
    blogPosting = ["blog"] # BlogPosting sections
    product = [] # Product sections

