languageCode                = "en-us"
title                       = "Tobyblog"
baseURL                     = "http://tobyblog.com/"
theme                       = "internet-weblog"
Paginate                    = 5
publishDir                  = "public"
SectionPagesMenu            = "Main"
DisqusShortname				= "tobyblog-com"

[author]
	Handle = "tobyblog"
	FirstName = "Toby"
	LastName = "Marks"
#	AboutPage = "/about"
	Location = "Dallas, TX"
	FlickrID = "75738497@N00"

[params]
	Description = "The personal blog and home page of one of the web's many Tobys. What distinguishes me is that I own the domain. To you I say welcome(!) in the grand old tradition of proto-websites of the nineties. The place where I deposit the overflow of my time, mind, and labors, Tobyblog is my refuge from the coming social media apocalypse."
	ShowCopyright = true
	RSSEnabled = true
	RSSSections = [ "Posts", "Microposts", "Photos", "Videos" ]
	RSSMicropostTitles = false
	YearlyMicroposts = true
	SummarizeMicroposts = false
	images = ["img/tobyblog-site-cover.jpg"]

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[[menu.main]]
	name = "Posts"
	weight = 1
	identifier = "posts"
	url = "/posts/"

[[menu.main]]
	name = "Microposts"
	weight = 2
	identifier = "microposts"
	url = "/microposts/"

[[menu.main]]
	name = "Photos"
	weight = 3
	identifier = "photos"
	url = "/photos/"

[[menu.main]]
	name = "Videos"
	weight = 4
	identifier = "videos"
	url = "/videos/"
