---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/photos
  label: Photos
  create: all
  match: "**/*"
- type: directory
  path: content/microposts
  label: Microposts
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: img
public_path: https://res.cloudinary.com/tobyblog/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
version: 0.54.0
